### ISSUE TITLE
1558M (XL) Download Missing

### ISSUE THREAD

**Issue by rmcc3** [dbddv01/GPT2Explorer#1]
The gpt2_1558M.bin file download is missing.

URL: https://drive.google.com/file/d/1HI5fyjZKP8yHQv3pLA1PiEp1wk7-QZOX/view?usp=sharing

![2021-02-04 19_14_07-Page Not Found](https://user-images.githubusercontent.com/2359196/106971567-2bb61d80-671d-11eb-91f8-1d9abbdda1a4.png)

**Comment by urgheuigrpauipeg** [comment]
This needs to be fixed soon, i have a copy i could upload if you really need it.

**Comment by dbddv01** [comment]
Hi, sorry, wrong manipulation from my side, i will reupload before end of day CET.

**Comment by dbddv01** [comment]
file restored.

**Comment by Notekan** [comment]
Hi. This file is missing again. I really wanted to check it out.

**Comment by dbddv01** [comment]
permission issue. sorry. should be visible now.

**Comment by Notekan** [comment]
Hi again. I tried to download it again, but it says: "Sorry, the file you have requested does not exist." All other links for smaller models work, but not this one. I would be extremely grateful if I would have possibility to download 1558M (XL) model. I have so much fun with this app. It would be amazing if I could use biggest model :)

**Comment by dbddv01** [comment]
Thanks for your comment. I did not notice that the a new link was generated. 
So this one works for me from other accounts. Tell me if ok for you. 
I shall update the doc accordingly soon if ok. 
https://drive.google.com/file/d/1wH6cJy78IT_c68gh3M1kuR82Pi1pG2Xl/view?usp=sharing
